DROP TABLE IF EXISTS spectral_reading;

CREATE TABLE spectral_reading (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 value_1 FLOAT NOT NULL,
 value_2 FLOAT NOT NULL,
 value_3 FLOAT NOT NULL,
 value_4 FLOAT NOT NULL,
 value_5 FLOAT NOT NULL,
 value_6 FLOAT NOT NULL,
 value_7 FLOAT NOT NULL,
 value_8 FLOAT NOT NULL,
 value_9 FLOAT NOT NULL,
 value_10 FLOAT NOT NULL,
 value_11 FLOAT NOT NULL,
 value_12 FLOAT NOT NULL,
 value_13 FLOAT NOT NULL,
 value_14 FLOAT NOT NULL,
 value_15 FLOAT NOT NULL,
 value_16 FLOAT NOT NULL,
 value_17 FLOAT NOT NULL,
 value_18 FLOAT NOT NULL
);